- name: Install MongoDB 3.2
  hosts: db
  become: true
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present

  # Подключаем репозиторий с пакетами mongodb
  - name: Add repository
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
      state: present

  - name: Update
    apt:
      update_cache: yes

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
      state: started